"""Add views and avg_read time fields

Revision ID: b2332d247d62
Revises: a2ee62b127b7
Create Date: 2025-04-22 16:12:15.414060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2332d247d62'
down_revision = 'a2ee62b127b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_read_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('avg_read_time')
        batch_op.drop_column('views')

    # ### end Alembic commands ###
